# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mn4pWMrF7dugWjz9XT0nZAPG11yetAl2
"""

x = 12
y= 32
z = x + y
print(z)